apiVersion: apps/v1
kind: Deployment
metadata:
  name: promotion-service
  namespace: next-me
  labels:
    app: promotion-service
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  selector:
    matchLabels:
      app: promotion-service
  template:
    metadata:
      labels:
        app: promotion-service
    spec:
      imagePullSecrets:
        - name: ghcr-cred
      containers:
        - name: promotion-service
          image: ghcr.io/sparta-next-me/promotion-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 13000

          envFrom:
            - secretRef:
                name: promotion-service-env

          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: "true"
            - name: SPRING_CONFIG_IMPORT
              value: "optional:configserver:http://config-server.next-me.svc.cluster.local:3100"
            - name: SPRING_CLOUD_CONFIG_NAME
              value: "promotion-service"
            - name: JAVA_OPTS
              value: "-Xms512m -Xmx768m"

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 13000
            initialDelaySeconds: 150
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 13000
            initialDelaySeconds: 200
            periodSeconds: 20

          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: promotion-service
  namespace: next-me
spec:
  selector:
    app: promotion-service
  ports:
    - name: http
      port: 13000
      targetPort: 13000
  type: ClusterIP